version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 955224149011.dkr.ecr.us-east-1.amazonaws.com/chat ./chat-service
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 955224149011.dkr.ecr.us-east-1.amazonaws.com/chat:latest
      - echo Writing image definitions file...
      - printf '[{"name":"chat","imageUri":"%s"}]' 955224149011.dkr.ecr.us-east-1.amazonaws.com/chat:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'


